CREATE TABLE Person
(
	id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	firstname  VARCHAR(100) NOT NULL,
	lastname   VARCHAR(100) NOT NULL,
	streetname VARCHAR(150),
	streetno VARCHAR(10),
	zipcode VARCHAR(10),
	city VARCHAR(100),
	country VARCHAR(100),
	mailbox VARCHAR(100),
	phonenumber VARCHAR(100),
	cellphone VARCHAR(100)
);
